networks:
  nginx-proxy-manager_default:
    external: true
services:
  leistungserfassung:
    image: registry.gitlab.com/ko-soft/leistungserfassung:dev
    ports:
      - "8090:80"
    networks:
      - nginx-proxy-manager_default
    labels:
      # Hiermit gibst du Watchtower grünes Licht für diesen Container
      - "com.centurylinklabs.watchtower.enable=true"
